# Generated by Django 5.1 on 2024-08-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='prompt',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
